auto:   true
server: true


name: avplayer 社区
url: http://avplayer.org
description: 中国技术第一的开源社区

permalink: date
pygments: true
markdown: rdiscount
baseurl: /


github:
   username: microcai
   
domain: avplayer.org

source: .
destination: ./_site
plugins: ./_plugins
